# Server configurations
server:
  port: 8080

# Database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomorrowland
    username: root
    password: mukul
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# Swagger configurations
swagger:
  enabled: true
    